platform:ios,'9.0'

inhibit_all_warnings!

use_frameworks!

pre_install do
    system("sed -i '' '/UITextField/d' Pods/BlocksKit/BlocksKit/BlocksKit+UIKit.h")
    system('rm Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.h')
    system('rm Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.m')
end

target ‘iOS’ do

    pod 'Masonry', '1.1.0'
    pod 'SVProgressHUD', '2.2.5'
    pod 'AFNetworking', '3.2.0'
    pod 'SDWebImage', '4.3.3'
    pod 'Reachability', '3.2'
    pod 'FMDB', '2.7.2'
    pod 'MJRefresh', '3.1.15.3'
    pod 'Base64', '1.1.2'
    pod 'SFHFKeychainUtils', '1.0.0'
    pod 'SDCycleScrollView', '1.75'
    pod 'MJExtension', '3.0.13'
    pod 'BlocksKit', '2.2.5'
    pod 'AspectsV1.4.2', '1.4.2'
    pod 'WZLBadge', '1.2.5'
    pod 'SwipeTableView', '0.2.6'
    pod 'YYText', '1.0.7'
    pod 'TZImagePickerController', '2.1.0.3'
    pod 'BRPickerView', '2.2.1'
    pod 'ZYKeyboardUtil', '1.0.7'
    pod 'LYEmptyView'
end
