platform:ios,'9.0'

inhibit_all_warnings!

use_frameworks!

pre_install do
    system("sed -i '' '/UITextField/d' Pods/BlocksKit/BlocksKit/BlocksKit+UIKit.h")
    system('rm Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.h')
    system('rm Pods/BlocksKit/BlocksKit/UIKit/UITextField+BlocksKit.m')
end

target ‘iOS’ do

    pod 'Masonry'
    pod 'SVProgressHUD'
    pod 'AFNetworking'
    pod 'Reachability'
    pod 'FMDB'
    pod 'MJRefresh'
    pod 'Base64'
    pod 'SFHFKeychainUtils'
    pod 'SDCycleScrollView'
    pod 'MJExtension'
    pod 'BlocksKit'
    pod 'AspectsV1.4.2'
    pod 'WZLBadge'
    pod 'SwipeTableView'
    pod 'YYText'
    pod 'TZImagePickerController'
    pod 'BRPickerView'
    pod 'ZYKeyboardUtil'
    pod 'LYEmptyView'
end
